package models

import (
	"fmt"
	"time"

	"github.com/LH-10/mylistr/pkg/dbconfig"
	"github.com/jmoiron/sqlx"
	"github.com/lib/pq"
)

type GameDetail struct {
	GameID      int64          `db:"game_id" json:"id"`
	GameName    string         `db:"game_name" json:"title"`
	ReleaseDate time.Time      `db:"release_date" json:"release"`
	Rating      int            `json:"rating"`
	Developer   pq.StringArray `db:"developer" json:"developers"`
	Publisher   pq.StringArray `json:"publishers"`
	HeaderImage string         `db:"header_image" json:"banner"`
	Description string         `json:"description"`
	Tags        pq.StringArray `json:"tags"`
}

const schema = `

CREATE TABLE IF NOT EXISTS game_details (
	game_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	game_name VARCHAR(255),
	release_date TIMESTAMPTZ,
	rating VARCHAR(255),
	developer text[],
	publisher text[],
	header_image VARCHAR,
	description TEXT,
	tags text[]
	);

`

var db *sqlx.DB

func init() {
	db = dbconfig.GetDB()
	db.MustExec(schema)
}

const GetGameRecord string = `Select * from game_details where id=:id`

func (gm *GameDetail) GetRecord(admin_id int64) (int64, error) {
	tx, err := db.Beginx()
	if err != nil {
		fmt.Println(err)
		return -1, err
	}
	defer tx.Rollback()
	err = tx.Get(gm, GetGameRecord)
	if err != nil {
		fmt.Println(err)
	}
	return -1, err

}

func (gm *GameDetail) InsertData(admin_id int64) (int64, error) {
	tx, err := db.Beginx()
	if err != nil {
		fmt.Println(err)
		return -1, err
	}

	defer tx.Rollback()
	stmt, err := tx.PrepareNamed("Insert INTO game_details(game_name,release_date,rating,developer,publisher,description,tags,header_image) VALUES(:game_name,:release_date,:rating,:developer,:publisher,:description,:tags,:header_image) RETURNING game_id")
	if err != nil {
		fmt.Println(err)
		return -1, err
	}
	// stmt = tx.NamedStmt(stmt)
	var effectid int64
	err = stmt.QueryRow(*gm).Scan(&effectid)
	if err != nil {
		fmt.Println(err)
		return -1, err
	}

	_, err = tx.Exec("Insert into admin_tracker(admin_id,game_id) values($1,$2)", admin_id, effectid)
	if err != nil {
		fmt.Println(err)
		return -1, err
	}

	if err = tx.Commit(); err != nil {
		return -1, err
	}

	return effectid, nil
}
