package models

import (
	"fmt"
	"time"

	"github.com/LH-10/mylistr/pkg/dbconfig"
	"github.com/jmoiron/sqlx"
)

type GameDetail struct {
	GameID      string    `db:"game_id"`
	GameName    string    `db:"game_name" json:"title"`
	ReleaseDate time.Time `db:"release_date" json:"release"`
	Rating      int
	Developer   []string `json:"developers"`
	Publisher   []string `json:"publishers"`
	HeaderImage string   `db:"header_image"`
	Description string
	Tags        []string
}

const schema = `

CREATE TABLE IF NOT EXISTS game_details (
	game_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	game_name VARCHAR(255),
	release_date TIMESTAMPTZ,
	rating VARCHAR(255),
	developer VARCHAR(255)[],
	publisher VARCHAR(255)[],
	header_image VARCHAR,
	description TEXT,
	tags VARCHAR(255)[]
	);

`

var db *sqlx.DB

func init() {
	db = dbconfig.GetDB()
	db.MustExec(schema)
}

func (gm *GameDetail) InsertData() (int, error) {
	stmt, err := db.PrepareNamed("Insert INTO game_details(game_name,release_date,rating,header_image) VALUES(:game_name,:release_date,:rating,:header_image)")
	if err != nil {
		fmt.Println(err)
		return -1, err
	}
	effect, err := stmt.Exec(*gm)
	if err != nil {
		fmt.Println(err)
		return -1, err
	}
	effectid, err := effect.LastInsertId()
	if err != nil {
		return -1, err
	}
	return int(effectid), nil
}
